[build]
builder = "DOCKERFILE"

[deploy]
preDeployCommand = "sh deployment/railway_worker_predeploy.sh"
startCommand = "sh -lc \"bundle exec rails ip_lookup:setup && bundle exec sidekiq -C config/sidekiq.yml\""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
